### ISSUE TITLE
Multiple Head Unit Support

### ISSUE THREAD

**Issue by Corvetteguy19** [smithersDBQ/homebridge-fujitsu#1]
So the plugin works great with homekit, but there are a few settings missing.  As mentioned in the read me, it only supports one head unit.  I have two in my house connected to one compressor.  I would be more than happy to test and help to update the plugin for multiple head units.  Please reach out if this is something you’re willing to do.  Thanks

**Comment by joelk** [comment]
I've forked this plugin to add support for multiple heads. There's a PR open; until it's merged, you can install my fork with `npm install -g git+https://github.com/joelk/homebridge-fujitsu.git`.

**Comment by smithersDBQ** [comment]
Version 0.0.7 has been released with multiple unit support.  Thanks to @joelk for for his contribution.
