### ISSUE TITLE
Adding Second Ac 

### ISSUE THREAD

**Issue by DirtDiverMF** [smithersDBQ/homebridge-fujitsu#4]
Hi, 
Great job on this plugin! I have two units and would like to have control over the second one as well. It would be awesome if this can be added! or is there a way already?

Great work so far!
Keep it up.

**Comment by Corvetteguy19** [comment]
I’d love to see this too.

**Comment by JefConinx** [comment]
I have also two AC units and was wondering if I can be of anny assistance to help? I have a little bit of experience with programming, but i'm not familiar with this programming language. Would love to help though!

**Comment by joelk** [comment]
I've forked this plugin to add support for multiple heads. There's a PR open; until it's merged, you can install my fork with `npm install -g git+https://github.com/joelk/homebridge-fujitsu.git`.

**Comment by smithersDBQ** [comment]
Version 0.0.7 has been released with multiple unit support.  Thanks to @joelk for for his contribution.
