### ISSUE TITLE
Multiple AC

### ISSUE THREAD

**Issue by hitch3478** [smithersDBQ/homebridge-fujitsu#5]
Hy 
Anyone test With a switch case ?
I test the next week-end 
Thanks for this job

**Comment by joelk** [comment]
I've forked this plugin to add support for multiple heads. There's a PR open; until it's merged, you can install my fork with `npm install -g git+https://github.com/joelk/homebridge-fujitsu.git`.

**Comment by hitch3478** [comment]
Hy
there are an error
] device serial for AC000W002823337: undefined
[15/01/2021 à 21:43:27] [Split1] updated all for AC000W002823337
[15/01/2021 à 21:43:28] [Split1] Getting new token...
[15/01/2021 à 21:43:29] [Split1] API Access Token:
ad003162611b4bc8bcdeb4f6288bd02b
[15/01/2021 à 21:43:29] [Split1] Error: Auth expired
[15/01/2021 à 21:43:29] [Split1] Update Properties: Auth expired

**Comment by joelk** [comment]
> Hy there are an error ] device serial for AC000W002823337: undefined [15/01/2021 à 21:43:27] [Split1] updated all for AC000W002823337 [15/01/2021 à 21:43:28] [Split1] Getting new token... [15/01/2021 à 21:43:29] [Split1] API Access Token: ad003162611b4bc8bcdeb4f6288bd02b [15/01/2021 à 21:43:29] [Split1] Error: Auth expired [15/01/2021 à 21:43:29] [Split1] Update Properties: Auth expired Le ven. 15 janv. 2021 à 17:39, Joel Kin <notifications@github.com> a écrit :
> […](#)

Il marche correctement après ces erreurs? C'est normal pour le auth token d'expirer; après, le plugin devrait reauthenticater et continuer sans problèmes. Sinon, ce n'est pas mon amelioration, donc je ne peux pas probablement vous aider.

**Comment by hitch3478** [comment]
Non il ne fonctionne pas
On avait pas ces erreurs en 0.05

**Comment by joelk** [comment]
> Non il ne fonctionne pas On avait pas ces erreurs en 0.05 Le sam. 16 janv. 2021 à 17:44, Joel Kin <notifications@github.com> a écrit :
> […](#)

Désole… je ne sais assez comment ce plugin fonctionne pour le diagnoser d'ici. Peut-être @smithersDBQ pouvez vous aider avec le fonctionnement original de ce code? Ou peut-être mon amélioration ne marche pas en fait, ou marche seulement pour moi, et vous êtes le premier personne de trouver ça! ¯\_(ツ)_/¯

Ah non, je pense que je sais. Vous n'avez pas spécifié le `deviceIndex` dans le configuration, c'est ça? Si vous mettez "0", il marche? Comme ci:
![image](https://user-images.githubusercontent.com/1161662/104818103-56761b80-57da-11eb-85ad-50ff1ac0c807.png)

**Comment by smithersDBQ** [comment]
I am seeing the same issue when upgrading.  I am currently investigating.

**Comment by smithersDBQ** [comment]
The problem was the the "deviceIndex": "0" was not in the accessory config.  The update did not add this key:value to the config file.  You have to go into settings for the plugin, or enter manually in the config file.

**Comment by joelk** [comment]
> The problem was the the "deviceIndex": "0" was not in the accessory config. The update did not add this key:value to the config file. You have to go into settings for the plugin, or enter manually in the config file.

That makes sense--I didn't try it as an upgrade. Do you know if this is something that can be specified in the package file? I guess the simplest solution though is just to default to 0, will put up a new commit for that momentarily.

**Comment by hitch3478** [comment]
It's Ok. All Work.
Thanks a lot for this job...
Have a nice day

**Comment by hitch3478** [comment]
Par contre en mode chauffage les ronds restent bleu
Au début ils sont orange ensuite ils passent bleu

**Comment by hitch3478** [comment]
Il serait mieux qu’en mode chauffage les ronds restent orange et qu’en mode
Clim il passe en bleu

**Comment by hitch3478** [comment]
Au démarrage 
![image](https://user-images.githubusercontent.com/77246928/104820198-91f10400-5833-11eb-8a26-598089168de0.jpeg)

Ensuite 
![image](https://user-images.githubusercontent.com/77246928/104820224-b8af3a80-5833-11eb-92e8-c84206eccda8.jpeg)

**Comment by smithersDBQ** [comment]
Yes, I saw that too.  Version 0.0.6 will fix that.  I am testing now.  There Should be an official release in the next hour.

Oui, j'ai vu ça aussi. La version 0.0.6 corrigera cela. Je teste maintenant. Il devrait y avoir une sortie officielle dans l'heure qui suit.

**Comment by hitch3478** [comment]
Super merci bcp


Le sam. 16 janv. 2021 à 19:57, Ryan Beggs <notifications@github.com> a
écrit :

**Comment by smithersDBQ** [comment]
Version 0.0.7 has been released with multiple unit support.  Thanks to @joelk for for his contribution.
